### ISSUE TITLE
Micro-G & Xdrip ANR errors

### ISSUE THREAD

**Issue by atomspring** [nift4/Mint-OS#2]
**Describe the bug**
Hi, I use a bluetooth app to connect with a blood-sugar meter. The app works fine on most versions of Android (7 & 8), but I am having trouble with it on Mint-OS, looks like the app is requesting a message from MicroG but isn't getting a proper reply, this jams up the main thread and causes an ANR to be displayed.

**To Reproduce**
1. Install Mint, Magisk & system install of MicroG
2. Provide permission to fakestore via adb
3. Enable google device registration
4. enable google cloud messaging
5. Register phone by dialing *#*#CHECKIN#*#*
6. check that all is OK with microG, status is checked for everything
7. install Xdrip+ 8ba59ae-2020.03.11, verify everything syncs up ok with phone (at first)

**Expected behavior**
Phone should check-in with bluetooth device every 5-10 minutes to get a status update.

**Smartphone (please complete the following information):**
 - Device: cedric
 - OS Version: Mint 17.1-20200615
 - MicroG 0.2.10.19420 via Nanodroid installer

**Additional context**
When I disable regstration for Xdrip+ in the MicroG control panel, the app behaves fine, no issues with connectivity. Otherwise, there's an ANR every few minutes. I've attached the ANR & relevant logcat:
[Xdrip Errors.zip](https://github.com/nift4/Mint-OS/files/4828950/Xdrip.Errors.zip)

**Comment by nift4** [comment]
Try reinstalling/updating the app

**Comment by atomspring** [comment]
Still having the issue, goes away when the app is unregistered. Was there a change in how microG and Android 10 interact vs Android 7?

-------- Original Message --------
On Jun 25, 2020, 00:23, nift4 < notifications@github.com> wrote:
Try reinstalling/updating the app
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/nift4/Mint-OS/issues/2#issuecomment-649303262">https://github.com/nift4/Mint-OS/issues/2#issuecomment-649303262", "url": "[https://github.com](<a href=)/nift4/Mint-OS/issues/2#issuecomment-649303262">https://github.com/nift4/Mint-OS/issues/2#issuecomment-649303262", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by nift4** [comment]
Yes :/
microG is partially broken on Android 10 anyway, so I recommened just disabling registration

**Comment by nift4** [comment]
For Xdrip
