### ISSUE TITLE
Moto Gestures reset occasionally

### ISSUE THREAD

**Issue by atomspring** [nift4/Mint-OS#3]
**Describe the bug**
Sometimes when phone is left alone for some time, the setting for chop-chop activation of the flashlight is forgotten. Other gestures like fingerprint swiping are OK though.

**To Reproduce**
It's a Heisenbug, the issue appears at random and disappears when I try to find it. Nothing obvious in logcat.

**Expected behavior**
Gesture settings should "stick".

**Screenshots**
Not applicable.

**Smartphone (please complete the following information):**
 - Device: cedric
 - OS Version: 2020.06.15

Sorry I can't provide more detail, if/when I catch a logcat of the bug I'll happily provide it.

**Comment by atomspring** [comment]
Forgot to mention, once I disable and re-enable the setting for chop-chop, everything works again.

**Comment by nift4** [comment]
Moto Actions is maintained by the Lineage developers, please report this to them. Sorry, but I can't help you.
