### ISSUE TITLE
Mintos for pl2

### ISSUE THREAD

**Issue by kiam001** [nift4/Mint-OS#7]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated thats Mintos Not give for pl2

**Describe the solution you'd like**

Make pl2 ready for Mint i can give source for tree or you can it get self (17.1 is lineage offical)

**Describe alternatives you've considered**

Do nothing for pl2

**Additional context**
Dont know

**Comment by nift4** [comment]
what kernel version

**Comment by kiam001** [comment]
https://github.com/LineageOS/android_kernel_nokia_sdm660

**Comment by kiam001** [comment]
https://github.com/LineageOS/android_device_nokia_PL2
https://github.com/LineageOS/android_device_nokia_sdm660-common
https://github.com/TheMuppets/proprietary_vendor_nokia

**Comment by nift4** [comment]
kernel is new enough for not needing patches, cool. Can I have local manifest

**Comment by nift4** [comment]
oh wait
it's official so it should be included right

**Comment by nift4** [comment]
but I need one for vendor anyway ig

**Comment by nift4** [comment]
idk how that works

**Comment by nift4** [comment]
so except for manifest it is done

**Comment by kiam001** [comment]
all links what you need have i post here

**Comment by kiam001** [comment]
Kernel https://github.com/LineageOS/android_kernel_nokia_sdm660
Device https://github.com/LineageOS/android_device_nokia_PL2
Common https://github.com/LineageOS/android_device_nokia_sdm660-common
Vendor https://github.com/TheMuppets/proprietary_vendor_nokia

**Comment by kiam001** [comment]
more not needed

**Comment by nift4** [comment]
ok I'm done try to build
